# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e173cacd66bda330085849d68058562d35c2d34c16dae9a5599be5cf69655435d287063ce61370d9a75fac14ed0447547abf8b734d3501f3b5e9d9c0bfead7e7

test:
  secret_key_base: 3664b91134761be64f077183ddd6ea99e36ebc4bf838276e4e842208f50d64cbaf473b617aa5d54be0ef63d62754a960203dc404a3cf8cdd8b3311daaf8d3588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
